### ISSUE TITLE
Not able to understand how to install the script

### ISSUE THREAD

**Issue by Welstand** [lucasrla/remarks#22]
Hi, would it be possible to make a Wiki for people like me who don't understand _anything_ of programming? I really want/need to use the script, so it's quite frustrating not understanding how to do it.

**Comment by akelai** [comment]
For which OS you’re most interested in?

**Comment by Welstand** [comment]
macOS Big Sur Version 11.2.2

**Comment by lucasrla** [comment]
Hey @Welstand,

To run `remarks`, you need just two things: `git` and `python`. Python 3.8 comes pre-installed with macOS Big Sur. So the only new thing you need is git. There are several ways to install it. A straightforward one is described here: https://docs.github.com/en/github/getting-started-with-github/set-up-git

There is a catch with Apple's default Python, though. [Apple ships both `python2` and `python3` on macOS Big Sur](https://apple.stackexchange.com/questions/406244/will-macos-big-sur-remove-the-default-python-installation-for-good). Because `remarks` needs Python `>= 3.8` you must use the command `python3` and `pip3` and not simply `python` and `pip` (which unfortunately point to `python2`).

Now, just open your terminal and type the following:

```sh
# Download remarks to your machine
git clone https://github.com/lucasrla/remarks.git && cd remarks

# Install the dependencies
pip3 install -r requirements.txt

# Run it and learn the features that are available
python3 -m remarks --help
```

Please let us know if you run into any problems.

PS: I have just enabled the Wiki feature. It is open for anyone to edit/write it: https://github.com/lucasrla/remarks/wiki. Feel free to document your steps there so that future users can learn as well.

PPS: I will convert this issue to a discussion. It seems more appropriate there.
